# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d996157a4e77d4dd0955701b6d7effd791b15b07277672ab536596091cae0e701857449ef409cac99c9392a663fdf26251a33fcbb15e000b8ff621ddb56f8693

test:
  secret_key_base: c8b78fd975461023018471da4fd9ae27272aae49a231b7498cb9515688d5cf919d21668742606e52bc694b042d58f908d20c4c87ca0e8710f66a43141fcce4e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
